# Generated by Django 4.2 on 2023-04-11 03:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tareas', '0003_alter_tareas_fecha_termino'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tareas',
            new_name='lastareas',
        ),
    ]
